### ISSUE TITLE
Pressing [e] cancels new reminder

### ISSUE THREAD

**Issue by odegroot** [Dem1se/SDVMods#15] opened 2021-11-29 16:00 UTC
## Steps to reproduce

- Have `e` key bound to "Access Menu" (AFAIK this is the default)
- Open the "New Reminder" dialog (F2)
- Set the focus / cursor to the "Reminder Message" field
- Enter any message text that contains an `e`, e.g. 'island harvest ready'

## Expected

The dialog accepts the message and waits for further input.

## Actual

The dialog closes and the reminder is cancelled.

When I try again, sometimes I can successfully enter the message and create the reminder, but most of the time the reminder is inadvertently cancelled.

**Comment by Dem1se** [comment] 2021-11-30 08:55
Hey. This issue was fixed in v1.2.1, so I'm not sure what's happening. Can you give me more info about:
- the version of the mod you're using
- the operating system you're on
- Whether you're in a single-player, or co-op game (in which case whether you're the host or a farmhand)

Thanks.

**Comment by odegroot** [comment] 2021-11-30 14:55
I used _CustomReminders v2.0.0-6215-2-0-0-1630752115.zip_, which is currently the default file offered by nexusmods.
https://www.nexusmods.com/stardewvalley/mods/6215?tab=files&file_id=44792

Perhaps this is a regression in v2.0 resulting from the merger with RecurringReminders?

I'm on Win10, and am playing a single player game.

**Comment by Dem1se** [comment] 2021-11-30 18:05
I tried reproducing the bug by using the downloaded version after deleting the current install, but I'm still not able to.
No button other than [Esc] closes the menu for me. I checked the code to suppress the inventory button when using the mod, it wasn't affected in the merger, and remains in place and functional.

Can you post you logs here through this: https://smapi.io/log

and maybe also embed your config here if you have made any changes to it.

Thanks.

**Comment by odegroot** [comment] 2021-11-30 20:47
Hmm that is interesting, thank you for testing.

I just tried again and the behavior remains the same. Here's the log.
https://smapi.io/log/86f6c3dbced74c77b6feabdebadbeca0
I literally just started the game, loaded a save, pressed `F2` to create a new reminder, typed some random `asdfddf`, that worked fine, typed an `e`, the dialog closed. After that I closed the game.
I did not touch the config.json but I still attached it for completeness. (renamed since github doesn't allow .config)
[config.json](https://github.com/Dem1se/SDVMods/files/7628743/config.json.txt)

As you can see I'm running some other mods as well, perhaps there's some conflict between two of them?

**Comment by odegroot** [comment] 2021-11-30 21:42
I see that you call `Helper.Input.Suppress(Utilities.Globals.MenuButton)` within the `draw(…)` method.

Looking at [the docs for this function](https://stardewvalleywiki.com/Modding:Modder_Guide/APIs/Input#Suppress_input), it says that this method only suppresses a single button press.
> This suppression will remain in effect until the player releases the button.

I believe that suppressing a button-press in the draw method is unreliable. I think this should be done in the event handler for `ButtonsChanged` or `ButtonPressed` to make it robust ([docs](https://stardewvalleywiki.com/Modding:Modder_Guide/APIs/Events#Input)).

Here's an example of some other mod that suppresses keys. It does the suppression in the `ButtonsChanged` event handler.
https://github.com/Deflaktor/KeySuppressor/blob/master/KeySuppressor/ModEntry.cs

**Comment by Dem1se** [comment] 2021-12-13 15:32
It seems that the way the mod used to find the menu button to suppress might not be reliable anymore, possible due to changes to the savefile's content/structure.

I've release a v2.1.1-beta1 with a minor fix, please let me know if it fixes the issue.

Thanks!

**Comment by Dem1se** [comment] 2021-12-19 10:22
Yeah according to another bug report, v2.1.1-beta1 fixed it. I'll release it shortly.
Thanks for bringing this up.

**Closed by Dem1se** 2021-12-19 10:22 UTC
